export const FACULTIES: string[] = [
  "Akademija dramske umjetnosti, Sveučilište u Zagrebu",
  "Akademija likovnih umjetnosti, Sveučilište u Zagrebu",
  "Akademija primijenjenih umjetnosti, Sveučilište u Rijeci",
  "Akademija za umjetnost i kulturu u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Agronomski fakultet, Sveučilište u Zagrebu",
  "Arhitektonski fakultet, Sveučilište u Zagrebu",
  "EFFECTUS veleučilište",
  "Edukacijsko-rehabilitacijski fakultet, Sveučilište u Zagrebu",
  "Ekonomski fakultet u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Ekonomski fakultet u Splitu, Sveučilište u Splitu",
  "Ekonomski fakultet u Rijeci, Sveučilište u Rijeci",
  "Ekonomski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Evanđeosko teološko veleučilište",
  "Fakultet agrobiotehničkih znanosti Osijek, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet elektrotehnike i računarstva, Sveučilište u Zagrebu",
  "Fakultet elektrotehnike, računarstva i informacijskih tehnologija Osijek, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet elektrotehnike, strojarstva i brodogradnje u Splitu, Sveučilište u Splitu",
  "Fakultet filozofije i religijskih znanosti, Sveučilište u Zagrebu",
  "Fakultet građevinarstva, arhitekture i geodezije u Splitu, Sveučilište u Splitu",
  "Fakultet hrvatskih studija, Sveučilište u Zagrebu",
  "Fakultet kemijskog inženjerstva i tehnologije, Sveučilište u Zagrebu",
  "Fakultet organizacije i informatike, Sveučilište u Zagrebu",
  "Fakultet političkih znanosti, Sveučilište u Zagrebu",
  "Fakultet primijenjene matematike i informatike, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet prometnih znanosti, Sveučilište u Zagrebu",
  "Fakultet strojarstva i brodogradnje, Sveučilište u Zagrebu",
  "Fakultet turizma i ruralnog razvoja u Požegi, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet za dentalnu medicinu i zdravstvo Osijek, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet za forenzičke znanosti, Sveučilište u Splitu",
  "Fakultet za menadžment u turizmu i ugostiteljstvu, Sveučilište u Rijeci",
  "Fakultet za odgojne i obrazovne znanosti, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Fakultet zdravstvenih studija, Sveučilište u Rijeci",
  "Fakultet zdravstvenih znanosti, Sveučilište u Splitu",
  "Fakultet znanosti o moru, Sveučilište u Splitu",
  "Farmaceutsko-biokemijski fakultet, Sveučilište u Zagrebu",
  "Filozofski fakultet u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Filozofski fakultet u Rijeci, Sveučilište u Rijeci",
  "Filozofski fakultet u Splitu, Sveučilište u Splitu",
  "Filozofski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Geodetski fakultet, Sveučilište u Zagrebu",
  "Geotehnički fakultet, Sveučilište u Zagrebu",
  "Građevinski fakultet u Rijeci, Sveučilište u Rijeci",
  "Građevinski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Građevinski i arhitektonski fakultet Osijek, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Grafički fakultet, Sveučilište u Zagrebu",
  "Hrvatsko katoličko sveučilište",
  "Istarsko veleučilište, Pula",
  "Katolički bogoslovni fakultet u Đakovu, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Katolički bogoslovni fakultet u Splitu, Sveučilište u Splitu",
  "Katolički bogoslovni fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Kemijsko-tehnološki fakultet u Splitu, Sveučilište u Splitu",
  "Kineziološki fakultet u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Kineziološki fakultet u Splitu, Sveučilište u Splitu",
  "Kineziološki fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Libertas međunarodno sveučilište",
  "Medicinski fakultet u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Medicinski fakultet u Rijeci, Sveučilište u Rijeci",
  "Medicinski fakultet u Splitu, Sveučilište u Splitu",
  "Medicinski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Međimursko veleučilište u Čakovcu",
  "Metalurški fakultet, Sveučilište u Zagrebu",
  "MUP-Veleučilište kriminalistike i javne sigurnosti",
  "Muzička akademija, Sveučilište u Zagrebu",
  "Odjel za biologiju, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Odjel za fiziku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Odjel za kemiju, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Pomorski fakultet u Rijeci, Sveučilište u Rijeci",
  "Pomorski fakultet u Splitu, Sveučilište u Splitu",
  "Poslovno veleučilište Zagreb",
  "Pravni fakultet u Osijeku, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Pravni fakultet u Rijeci, Sveučilište u Rijeci",
  "Pravni fakultet u Splitu, Sveučilište u Splitu",
  "Pravni fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Prehrambeno-biotehnološki fakultet, Sveučilište u Zagrebu",
  "Prehrambeno-tehnološki fakultet Osijek, Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Prirodoslovno-matematički fakultet u Splitu, Sveučilište u Splitu",
  "Prirodoslovno-matematički fakultet u Zagrebu, Sveučilište u Zagrebu",
  "RIT Croatia",
  "Rudarsko-geološko-naftni fakultet, Sveučilište u Zagrebu",
  "Stomatološki fakultet, Sveučilište u Zagrebu",
  "Sveučilište Algebra Bernays",
  "Sveučilište Josipa Jurja Strossmayera u Osijeku",
  "Sveučilište Jurja Dobrile u Puli",
  "Sveučilište obrane i sigurnosti \"Dr. Franjo Tuđman\"",
  "Sveučilište Sjever",
  "Sveučilište u Slavonskom Brodu",
  "Sveučilište u Zadru",
  "Sveučilište VERN'",
  "Sveučilišni odjel za stručne studije, Sveučilište u Splitu",
  "Tehničko veleučilište u Zagrebu",
  "Tehnički fakultet u Rijeci, Sveučilište u Rijeci",
  "Tekstilno-tehnološki fakultet, Sveučilište u Zagrebu",
  "Učiteljski fakultet u Rijeci, Sveučilište u Rijeci",
  "Učiteljski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Umjetnička akademija u Splitu, Sveučilište u Splitu",
  "Fakultet biotehnologije i razvoja lijekova, Sveučilište u Rijeci",
  "Fakultet dentalne medicine, Sveučilište u Rijeci",
  "Fakultet informatike i digitalnih tehnologija, Sveučilište u Rijeci",
  "Fakultet za fiziku, Sveučilište u Rijeci",
  "Fakultet za matematiku, Sveučilište u Rijeci",
  "Fakultet šumarstva i drvne tehnologije, Sveučilište u Zagrebu",
  "Veleučilište \"Lavoslav Ružička\" u Vukovaru",
  "Veleučilište \"Marko Marulić\" u Kninu",
  "Veleučilište \"Nikola Tesla\" u Gospiću",
  "Veleučilište Algebra Bernays",
  "Veleučilište Arca",
  "Veleučilište ASPIRA",
  "Veleučilište Baltazar Zaprešić",
  "Veleučilište Hrvatsko zagorje Krapina",
  "Veleučilište Ivanić-Grad",
  "Veleučilište menadžmenta i sigurnosti SECURUS",
  "Veleučilište PAR",
  "Veleučilište RRiF",
  "Veleučilište studija sigurnosti",
  "Veleučilište suvremenih informacijskih tehnologija",
  "Veleučilište u Bjelovaru",
  "Veleučilište u Karlovcu",
  "Veleučilište u Križevcima",
  "Veleučilište u Rijeci",
  "Veleučilište u Šibeniku",
  "Veleučilište u Virovitici",
  "Veleučilište Velika Gorica",
  "Veterinarski fakultet u Zagrebu, Sveučilište u Zagrebu",
  "Zdravstveno veleučilište",
  "Zagrebačka škola ekonomije i managementa",
];
