version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    restart: always
    env_file:
      - .env.example
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: ../.docker/backend/Dockerfile
    restart: always
    env_file:
      - ./backend/.env.example
      - ./backend/.env

  minio:
    image: quay.io/minio/minio:RELEASE.2021-10-02T16-31-05Z
    command: server --console-address ":9001" /data/minio
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASS}"
    volumes:
      - ./.docker/minio/data:/data/minio
    env_file:
      - ./backend/.env.example
      - ./backend/.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  proxy:
    image: caddy:alpine
    restart: always
    volumes:
      - "./.docker/proxy/Caddyfile:/etc/caddy/Caddyfile:ro"
